### PR TITLE
docs: updated filepaths for schema store regex

### PR DESCRIPTION
**Pull request by james-milligan**
Signed-off-by: James Milligan <james@omnant.co.uk>

## This PR

- updates file paths to conform to schema store regex

### CODE REVIEW

**Review by skyerus — APPROVED** [review]

**Review by Kavindu-Dodan — APPROVED** [review]

**Comment by beeme1mr** [comment]
Homebrew must be updated prior to making this change. Please also review if other repos are directly references those flagd configs.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/flagd.rb#L41

**Comment by beeme1mr** [comment]
It may be safer to copy the existing examples instead of moving them. We'll just want to watch out for references to the old style so they can be updated.

**Review by beeme1mr — APPROVED** [review]
Please keep the original samples and add the new style next to them. We can then update all the references to the old style before completely removing them.

**Review by beeme1mr — CHANGES_REQUESTED** [review]
Please retain the original examples as well.

**Review by beeme1mr — APPROVED** [review]

**Pull request merged**
