### PR TITLE
feat: file extension detection

### PR DESCRIPTION
**Pull request by james-milligan**
Signed-off-by: James Milligan <james@omnant.co.uk>

## This PR

- file type is detected via the file extension, it is now possible to mix and match `json` and `yaml` files as flag configuration sources 

```
start -f file:./config/samples/example_flags.yaml -f file:./config/samples/example_flags.json
```

### Related Issues

https://github.com/open-feature/flagd/issues/240

### Follow-up Tasks

It is my opinion that the `-e` or `--evaluator` flag is now a little misleading / confusing, as only the `json_evaluator` is used internally, and changing the flag value has no effect internally. Open to opinions on how this should be handled, if at all.

### CODE REVIEW

**Comment by toddbaert** [comment]
> It is my opinion that the -e or --evaluator flag is not a little misleading / confusing, as only the json_evaluator is used internally, and changing the flag value has no effect internally. Open to opinions on how this should be handled, if at all.

I agree with this, but I'm not sure what the best approach is.

**Review by toddbaert — APPROVED** [review]

**Review by Kavindu-Dodan — APPROVED** [review]

**Comment by Kavindu-Dodan** [comment]
> > It is my opinion that the -e or --evaluator flag is not a little misleading / confusing, as only the json_evaluator is used internally, and changing the flag value has no effect internally. Open to opinions on how this should be handled, if at all.
> 
> I agree with this, but I'm not sure what the best approach is.

We only have one evaluator type and that's JSON (shared with yaml handling). So if we do not have any intention to introduce another evaluator, we can remove this option.

**Comment by beeme1mr** [comment]
> We only have one evaluator type and that's JSON (shared with yaml handling). So if we do not have any intention to introduce another evaluator, we can remove this option.

Can we think of any future scenario where we would want this? If not, I think it makes sense to deprecate this option.

**Comment by james-milligan** [comment]
> > We only have one evaluator type and that's JSON (shared with yaml handling). So if we do not have any intention to introduce another evaluator, we can remove this option.
> 
> Can we think of any future scenario where we would want this? If not, I think it makes sense to deprecate this option.

Ive just pushed the changes to deprecate the `-e`/`--evaluator` flag, a warning is logged when it is used

**Review by skyerus — APPROVED** [review]

**Review by beeme1mr — APPROVED** [review]

**Pull request merged**
