### PR TITLE
feat: s3 support for the blob sync

### LINKED ISSUE #1376: [FEATURE] Add S3-compatiblty sync source
### Requirements

A recent PR added support for [blob type sources](https://github.com/open-feature/flagd/pull/1366). This provides a nice abstraction on top of many popular cloud storage solutions. This can be leveraged to add S3 as a supported sync source.

### PR DESCRIPTION
**Pull request by djosephsen**
## This PR
Intent of this pr is to add S3 bucket support to the existing "blob" sync.

### Related Issues
fixes #1376 

### Notes
Marking as a draft for now until I can find my aws creds and live-test it. 

### Follow-up Tasks
integration testing is yet to be performed

### How to test
unit tests provided

### CODE REVIEW

**Review by beeme1mr — COMMENTED** [review]
Thanks! I'll try and test this E2E as soon as possible. In the meantime, could you please update the documentation to include s3 as a source?

**Review by beeme1mr — APPROVED** [review]
I've manually tested this and it works as expected. Thanks @djosephsen!

**Review by toddbaert — APPROVED** [review]
Thanks @djosephsen ! Great to have this.

**Comment by toddbaert** [comment]
@djosephsen I fixed some go.sum merge conflicts with main and force pushed back to your branch - no other changes. I hope you don't mind. Will merge when the CI passes.

cc @beeme1mr

**Comment by djosephsen** [comment]
this fell off my radar thanks, im at a corp onsite this week but I should be able to get back on this next week

**Pull request merged**
