### PR TITLE
chore: update CODEOWNERS

### PR DESCRIPTION
**Pull request by toddbaert**
I think that flagd and OFO are at the size and complexity that we need more CODEOWNERS. I think there's simply too many issues for a single person to keep up with.

I think 3 is a good number. It means that even if one CODEOWNER is away, there is one other person who can approve.

Relates to: https://github.com/open-feature/open-feature-operator/pull/265

### CODE REVIEW

**Review by skyerus — APPROVED** [review]

**Review by beeme1mr — APPROVED** [review]

**Comment by AlexsJones** [comment]
I absolutely agree with this, but I would really like to caution that I want to see us having a consensus on feature development @toddbaert There are some additions recently I am not totally convinced by or where the need has come from. Therefore I would like to request that we ensure a) anything above a chore is in the project board at least for visibility b) anything break or major is signalled at the office hours ( which I will setup again )

**Review by james-milligan — APPROVED** [review]

**Comment by beeme1mr** [comment]
Hey @AlexsJones, that sounds good. The project board we started during the last office hour should be fairly up-to-date. Let's chat at the next office hour to determine how we want to move issues from the `Backlog` to the `Todo` column. I think that would be a nice way to signal that a feature has been approved as work that should be done.

**Comment by AlexsJones** [comment]
Sure, happy to merge

**Comment by beeme1mr** [comment]
I'm going to merge this PR based on the last comment from @AlexsJones and the other outstanding PRs.

**Pull request merged**
