### PR TITLE
simplified pipelines

### PR DESCRIPTION
**Pull request by AlexsJones**
Our pipelines are doing two things 
- becoming hard to read
- pushing on main builds, we should be moving away from this and pinning to a release OCI in the OFO

### CODE REVIEW

**Review by thschue — APPROVED** [review]
lgtm

**Comment by thomaspoignant** [comment]
In this comment, https://github.com/open-feature/flagd/pull/51#discussion_r904154880 @toddbaert mentioned that he would prefer to have a new workflow for test/lint.

Are we all agree that this should be in the same file ?

**Comment by AlexsJones** [comment]
I didn't see the comment @thomaspoignant happy to revert if we have sound reasoning for distributing across files

**Comment by toddbaert** [comment]
@AlexsJones @thomaspoignant I'm fine with this how it is. I just wanted to keep the scaning / testing / linting separate from any pushing, which is no issue anymore since we are scanning a local image.

**Pull request merged**
