### PR TITLE
feat: snap

### PR DESCRIPTION
**Pull request by AlexsJones**
Adding snap configuration and badge

### CODE REVIEW

**Review by beeme1mr — COMMENTED** [review]
How does Snap pick up the changes?

**Review by toddbaert — APPROVED** [review]
I know very little about snaps, but I certainly trust @AlexsJones to, given his associations!

Along with @beeme1mr, I'm unsure how snapcraft.io "knows" about this package given there's no publish CI or anything here. Is snapcraft.io configured to look at the yaml file in this repo periodically?

**Review by beeme1mr — APPROVED** [review]
Agreed, this looks good. I would just like to understand the process a bit.

Thanks for putting this together @AlexsJones!

**Comment by AlexsJones** [comment]
> Agreed, this looks good. I would just like to understand the process a bit.
> 
> Thanks for putting this together @AlexsJones!

Currently this is adding in the settings for publishing, the publishing itself is still manual at this point e.g. you have to be logged in and run `snapcraft` what I will do is add a bit of documentation on how to manually release until we automate it

**Review by skyerus — APPROVED** [review]

**Review by james-milligan — APPROVED** [review]

**Pull request merged**
