### PR TITLE
refactor: isolate flag state management to store

### LINKED ISSUE #371: [chore] Refactor JsonEvaluator and isolate Flags to a store
`json_evaluator` [1] is the core evaluator currently used by flagd. Internally, it relies on `Flags` pushed from ISync implementations. 

The current implementation however lacks a good design with regards to Flag storage. For example, PR #370 focused on concurrent map access bug fix required mutexes in two locations. This shows that `json_evaluator` internals needs refactoring.

Consider the following proposal, 

image

Here, the  `json_evaluator` connects to `FlagStore` , which replaces the currently used `Flags` structure with defined contracts (exported methods). This makes FlagStore internals hidden from its consumer (json_evaluator), allowing clear interactions and modifications .
 
[1] - https://github.com/open-feature/flagd/blob/main/pkg/eval/json_evaluator.go

### PR DESCRIPTION
**Pull request by skyerus**
## This PR

- Isolates flag state management to store package

### Related Issues

Fixes #371 

### How to test

I've ran [flagd's integration tests](https://github.com/open-feature/flagd/pull/312) against this build to ensure behaviour is as before.

### CODE REVIEW

**Review by james-milligan — APPROVED** [review]

**Review by Kavindu-Dodan — APPROVED** [review]
Nice work :)

**Comment by beeme1mr** [comment]
Please quickly review the [high-level architecture](https://github.com/open-feature/flagd/blob/main/docs/other_resources/high_level_architecture.md) and make sure it doesn't need to be updated.

**Comment by skyerus** [comment]
> Please quickly review the [high-level architecture](https://github.com/open-feature/flagd/blob/main/docs/other_resources/high_level_architecture.md) and make sure it doesn't need to be updated.

Updated!

**Comment by Kavindu-Dodan** [comment]
> > Please quickly review the [high-level architecture](https://github.com/open-feature/flagd/blob/main/docs/other_resources/high_level_architecture.md) and make sure it doesn't need to be updated.
> 
> Updated!

Updates also look good per my view

**Pull request merged**
