### PR TITLE
ci: configure release please

### PR DESCRIPTION
**Pull request by beeme1mr**
## Overview

This PR enables [Release Please](https://github.com/googleapis/release-please) for managing automated release PRs. It works by looking at the git history of the main branch and automatically creating/updating a release PR. Conventional commit messages are used to determine the next release version. This repo has been configured to valid PR titles and use them as the commit message.

The flow has been tested end-to-end in a fork. You can see an example Release Please release PR [here](https://github.com/beeme1mr/flagd/pull/7). Once approved and merged, it triggers the release action. That can be seen [here](https://github.com/beeme1mr/flagd/actions/runs/2835311002). The action publishes the [flagD container](https://github.com/beeme1mr/flagd/pkgs/container/flagd/34510492?tag=v0.1.5) and updates the [GitHub release](https://github.com/beeme1mr/flagd/releases/tag/v0.1.5) to include the binaries.

## Noteworthy configurations

- Release Please has been configured to **NOT** bump the major version on a breaking changes until we've release a 1.0 version. The setting can be seen [here](https://github.com/open-feature/flagd/blob/54b42caf7153133dc682c5ee91d69be5bdec218f/release-please-config.json#L7).
- Goreleaser is still used but only runs after a Release Please PR has been merged. The setting can be seen [here](https://github.com/open-feature/flagd/blob/54b42caf7153133dc682c5ee91d69be5bdec218f/.github/workflows/release-please.yaml#L75).
- Image tags had to be set manually because the action was no longer triggered by a git tag. The setting can be seen [here](https://github.com/open-feature/flagd/blob/54b42caf7153133dc682c5ee91d69be5bdec218f/.github/workflows/release-please.yaml#L67-L69).

### CODE REVIEW

**Comment by AlexsJones** [comment]
Can you talk us through what this does? We already use [goreleaser](https://goreleaser.com/)

**Comment by beeme1mr** [comment]
Release Please opens and maintains a release PR by watching for changes that are merged into main. [Here's an example](https://github.com/open-feature/node-sdk-contrib/pull/89) of what a PR looks like. Once you're ready for a release, merging the PR will trigger a publish using go releaser. Release Please will handle bumping versions based on the conventional commits included in the release. This change should eliminate the need for setting a tag manually.

It looks like both release please and go release may try and publish release notes. I'll see if I can disable it in one of those tools.

**Comment by toddbaert** [comment]
It also makes cutting a release a democratic process (since a PR must be merged). It creates a release in github as usually, and can run any script you want on merge.

@beeme1mr I'm a bit confused here there... you seem to be running go-releaser, but not doing any of the docker build stuff. Is this script meant to replace the existing release workflow, or trigger the existing release workflow via a new tagged branch? Currently it seems to be doing something in-between... or am I confused?

**Comment by AlexsJones** [comment]
What are the steps for this to work then if I want to make a release with this integrated?

**Comment by AlexsJones** [comment]
Would like to see this demo'd before we commit to this personally.

**Comment by beeme1mr** [comment]
I'm happy to give a demo. Ping me when you have time.

You can try it yourself if you're interested by follow these steps:

1. Fork the repo and checkout this branch
2. Make a change in the fork and push it with a conventional commit message like "feat: add metaverse support". This can be pushed to main in your fork unless you've enabled branch protection.
3. After a few moments, there should be a PR opened by Release Please that contains a change log
4. Make another change and push with a commit message like "fix: prevent race condition during login"
5. After a few moments, the PR opened by Release Please should be updated to include both changes
6. Merging that PR triggers the normal release flow. It should create a GitHub release, build and attach the flagD binaries and push multi-arch docker images.

**Comment by AlexsJones** [comment]
Thanks Mike,

Just to clarify - github also generates the change log on a release. 
What is the key thing using release please does for us, automates the clicking of the release button?

**Comment by beeme1mr** [comment]
That's not a bad way to look at it. It also handles bumping the version number based on conventional commit messages. What is does is fairly simple but the workflow that it introduces comes with a number of benefits. For example, you know exactly what change haven't been release and the PR is subject to the same approval process as any other change. It can also be configured to change the version number in files. That could solve [this issue](https://github.com/open-feature/open-feature-operator/issues/46) if we decide to use Release Please in the operator.

**Comment by beeme1mr** [comment]
Here's an example PR from the node SDK.
https://github.com/open-feature/node-sdk/pull/155

**Comment by AlexsJones** [comment]
Im really not against it, but as the primary self-appointed release manager, I want to understand it more. Let's do a demo

**Comment by beeme1mr** [comment]
@AlexsJones, for consistency across the org, we're hoping to start using release please in all repos. Let's schedule a demo soon so we can merge or close this PR.

**Comment by AlexsJones** [comment]
> @AlexsJones, for consistency across the org, we're hoping to start using release please in all repos. Let's schedule a demo soon so we can merge or close this PR.

Lets get something in next week! I hope "we" is a collective representation of folks from OSS!

**Review by toddbaert — APPROVED** [review]
This all looks right to me.

**Review by AlexsJones — APPROVED** [review]

**Pull request merged**
