### PR TITLE
ci(release): add homebrew-core bump step

### LINKED ISSUE #306: Automatically bump version in Homebrew
## Overview

Flagd was recently [added to Homebrew](https://github.com/Homebrew/homebrew-core/pull/120187). The currently deployed version is [3.1](https://github.com/Homebrew/homebrew-core/pull/120541). This could quickly become out of sync if the update process isn't automated.

## Proposal

Add an additional step in [the release process](https://github.com/open-feature/flagd/blob/main/.github/workflows/release-please.yaml) to automatically open a PR in the [homebrew-core repo](https://github.com/Homebrew/homebrew-core).

## Resources

- https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#to-submit-a-version-upgrade-for-the-foo-formula
- https://github.com/mislav/bump-homebrew-formula-action

### PR DESCRIPTION
**Pull request by chenrui333**
## This PR

- feat(release): add homebrew-core bump step

### Related Issues

Fixes #306 

### Notes

Two TODOs with this PR:
- [x] Need to create a homebrew-core fork for which PAT token can access (https://github.com/open-feature/homebrew-core)
- [x] Need to create a repo scope token for this `COMMITTER_TOKEN` token

### How to test

- create a new release (it has been used by many other projects)

### CODE REVIEW

**Comment by beeme1mr** [comment]
Thanks @chenrui333! I'll work on the TODOs today.

**Review by beeme1mr — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @beeme1mr!!

**Comment by toddbaert** [comment]
@josecolella Can you confirm this looks good to you if you have some time?

**Review by toddbaert — APPROVED** [review]
LGTM, but I'm not that familiar with homebrew.

**Review by josecolella — APPROVED** [review]

**Pull request merged**
