### PR TITLE
refactor: migrate to connectrpc/connect-go

### LINKED ISSUE #790: Migrate from bufbuild/connect-go to connectrpc/connect-go
Migration instructions can be found below.

https://github.com/bufbuild/connect-go

### PR DESCRIPTION
**Pull request by craigpastro**
## This PR

Migrate from bufbuild/connect-go to connectrpc/connect-go.

### Related Issues

Closes #790.

### Follow-up Tasks

 I'll also create a PR in https://github.com/open-feature/go-sdk-contrib to migrate to connectrpc/connect-go for the flagd provider.

### CODE REVIEW

**Comment by craigpastro** [comment]
🤔 , maybe this is not as easy as I thought. I can't seem to get rid of
```
schemaV1 "buf.build/gen/go/open-feature/flagd/protocolbuffers/go/schema/v1"
```
The obvious replacement
```
schemaV1 "buf.build/gen/go/open-feature/flagd/connectrpc/go/schema/v1"
```
does not seem to exist.

**Comment by toddbaert** [comment]
@craigpastro I rebased on main and resolved conflicts (only in mod/sum files).

**Comment by toddbaert** [comment]
@odubajDT @thisthat @bacherfl we may want to release this before we deal with https://github.com/open-feature/flagd/issues/998

**Review by toddbaert — APPROVED** [review]

**Review by Kavindu-Dodan — APPROVED** [review]

**Comment by Kavindu-Dodan** [comment]
e2e tests have failed, gonna check this now

**Comment by Kavindu-Dodan** [comment]
> e2e tests have failed, gonna check this now

This is due to circular dependency. Let's go ahead with the change and update go provider this time - https://github.com/open-feature/flagd/issues/1004

**Pull request merged**
