### PR TITLE
ci: add pr name linter

### PR DESCRIPTION
**Pull request by beeme1mr**
Signed-off-by: Michael Beemer <michael.beemer@dynatrace.com>

### CODE REVIEW

**Review by thomaspoignant — APPROVED** [review]

**Comment by AlexsJones** [comment]
Before I agree to this, how do I open a PR now?

**Comment by beeme1mr** [comment]
@AlexsJones The title of a PR must follow the [conventional commits specification](https://www.conventionalcommits.org/en/v1.0.0/). The main prefixes are `fix` and `feat` because they directly affect the release notes and version number. Other prefixes can include: build, chore, ci, docs, style, refactor, perf, test.

**Comment by toddbaert** [comment]
> @AlexsJones The title of a PR must follow the [conventional commits specification](https://www.conventionalcommits.org/en/v1.0.0/). The main prefixes are `fix` and `feat` because they directly affect the release notes and version number. Other prefixes can include: build, chore, ci, docs, style, refactor, perf, test.

Yep - basically it's like semantic commits, but PR titles instead, which are easily editable.

**Review by toddbaert — APPROVED** [review]

**Comment by beeme1mr** [comment]
@AlexsJones any concerns? If not, I'm going to merge this change.

**Comment by AlexsJones** [comment]
> @AlexsJones any concerns? If not, I'm going to merge this change.

Looks fine to me, I'd suggest if we have to use `feat` as the prefix, feature branches should also be named that way

**Comment by beeme1mr** [comment]
> Looks fine to me, I'd suggest if we have to use `feat` as the prefix, feature branches should also be named that way

Is there a good way to automate that?

**Pull request merged**
