### PR TITLE
fix: bubbles up unclean error exits

### PR DESCRIPTION
**Pull request by AlexsJones**
Signed-off-by: Alex Jones <alexsimonjones@gmail.com>

https://github.com/open-feature/flagd/issues/169

### CODE REVIEW

**Review by beeme1mr — APPROVED** [review]
Looks good, thanks!

**Comment by beeme1mr** [comment]
Hey @AlexsJones, can you update the PR title to start with `fix` instead of `chore`? That will ensure the change properly bumps the version and is included in the release notes.

**Review by toddbaert — APPROVED** [review]
Make sense to me. Agree with @beeme1mr this should be a `fix` so it goes into the changelog automatically though.

**Comment by AlexsJones** [comment]
Just to be pedantic but this wasn't a bug

**Pull request merged**
